repository:
  default_branch: main

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - lint
          - test
      required_pull_request_reviews: true
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
