repository:
  default_branch: main

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - lint
          - test
          - build
      required_pull_request_reviews: true
      enforce_admins: false
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      bypass_pull_request_allowances:
        apps:
          - dependabot
