name: \u2753 Question
description: Ask a question about the project.
title: "[Question]: "
labels:
  - question
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Provide any background information.
