name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: echo "Linting..."

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: ./scripts/setup.sh
      - name: Test
        run: ./scripts/test.sh

  pr-title:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - id: pr_title_check
        uses: amannn/action-semantic-pull-request@v5
        if: github.repository == 'PtiCalin/temp_repo-gen'
        continue-on-error: true
        with:
          types: |
            feat
            fix
            docs
            chore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit format help
        if: steps.pr_title_check.outcome == 'failure'
        run: echo "Please see docs/conventions/commit-format.md" && exit 1
