name: Stale Bot

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale. Reply to keep it open.'
          stale-pr-message: 'This PR is stale. Reply to keep it open.'
          days-before-stale: 30
          days-before-close: 7
